apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  settings.yaml: |
    {{- .Values.config.settings | nindent 4 }}
  services.yaml: |
    {{- .Values.config.services | nindent 4 }}
  widgets.yaml: |
    {{- .Values.config.widgets | nindent 4 }}
  bookmarks.yaml: |
    {{- .Values.config.bookmarks | nindent 4 }}
  {{- if .Values.config.docker }}
  docker.yaml: |
    {{- .Values.config.docker | nindent 4 }}
  {{- end }}
  kubernetes.yaml: |
    {{- .Values.config.kubernetes | nindent 4 }}
  {{- if .Values.config.customCSS }}
  custom.css: |
    {{- .Values.config.customCSS | nindent 4 }}
  {{- end }}
